export const categories = {
  Collections: {
    name: "Collections",
    subcategories: [
      "Everyday Bras",
      "Underwear",
      "Specialty and Fashion Bras",
      "Panties",
      "Lingerie Sets",
      "Shapewear",
      "Swimwear",
      "One-Piece Swimsuits",
      "Bikinis",
      "Tankinis",
      "Luxury and Designer Collections",
      "Seasonal and Special Occasion Wear",
      "Monokinis",
      "Nightwear",
      "Pajama Sets",
      "Nightgowns",
      "Activewear",
      "Yoga Pants",
      "Sports Bras",
      "Beachwear",
      "Intimates and Accessories",
    ],
  },

  Underwears: {
    name: "Underwears",
    subcategories: [
      "Everyday Bras",
      "T-shirt Bra",
      "Full-Coverage Bra",
      "Wire-Free Bra",
      "Convertible Bra",
      "Racerback Bra",
      "Longline Bra",
      "Minimizer Bra",
      "Training Bra",
      "Specialty & Fashion Bras",
      "Push-Up Bra",
      "Sports Bra",
      "Bralette",
      "Strapless Bra",
      "Balconette Bra",
      "Underwire Bra",
      "Plunge Bra",
      "Demi Bra",
      "Maternity/Nursing Bra",
      "Shelf Bra",
      "Padded Bra",
      "Mastectomy Bra",
      "Intimates and Accessories",
      "Panties",
      "Shapewear",
      "Hosiery",
      "Camisoles & Tanks",
      "Slips",
      "Babydolls & Chemises",
      "Lingerie Accessories",
      "Sleep & Lounge",
      "Loungewear",
      "Nightwear",
      "Pajamas",
      "Robes",
      "Bodysuits",
    ],
  },
  Nightwears: {
    name: "Nightwears",
    subcategories: [
      "Seasonal & Occasion Wear",
      "Bridal Lingerie",
      "Bridal Sets",
      "Honeymoon Lingerie",
      "Holiday Lingerie",
      "Seasonal Collections",
      "Spring Collection",
      "Summer Collection",
      "Autumn Collection",
      "Winter Collection",
      "Loungewear",
      "Lounge Tops",
      "Lounge Pants",
      "Lounge Shorts",
      "Pajama Sets",
      "Shorts Sets",
      "Lounge Pants",
      "Pants Sets",
      "Nightgowns",
      "Short Nightgowns",
      "Long Nightgowns",
      "Sleep Wears",
      "Cotton Sleep Shorts",
      "Silk Sleep Shorts",
      "Standard Sleep Shirts",
      "Long Sleep Shirts",
      "Standard Sleep Rompers",
      "Lace Sleep Rompers",
    ],
  },
  "Swimwear & Beachwear": {
    name: "Swimwear & Beachwear",
    subcategories: [
      "Classic One-Piece",
      "Sporty One-Piece",
      "Cut-Out One-Piece",
      "Triangle Bikini",
      "Halter Bikini",
      "Bandeau Bikini",
      "High-Waisted Bikini",
      "Standard Tankini",
      "Long Tankini",
      "Classic Monokini",
      "Cut-Out Monokini",
      "Standard Swim Dress",
      "Skirted Swim Dress",
      "Rash Guards",
      "Short-Sleeve Rash Guards",
      "Long-Sleeve Rash Guards",
      "Swim Shorts",
      "Board Shorts",
      "Bikini Shorts",
      "Sport Swimsuits",
      "Competitive Swimsuits",
      "Water Sports Swimsuits",
      "Sarongs",
      "Kaftans",
      "Beach Dresses",
      "Beach Hats",
      "Beach Bags",
      "Sunglasses",
      "Sandals and Footwear",
      "Flip-Flops",
      "Sandals",
    ],
  },
  "Holiday Shop": {
    name: "Holiday Shop",
    subcategories: [
      "Tropical Vacation Wear",
      "Beach Accessories",
      "Tropical Swimwear",
      "Tropical Cover-Ups",
      "Ski Vacation Wear",
      "Thermal Underwear",
      "Thermal Leggings",
      "Bikinis",
      "Tankinis",
      "Seasonal and Special Occasion Wear",
      "Spring Collection",
      "Spring Lingerie",
      "Spring Nightwear",
      "Summer Collection",
      "Summer Swimwear",
      "Summer Loungewear",
      "Autumn Collection",
      "Winter Collection",
      "Winter Lingerie",
      "Intimates and Accessories",
      "Special Occasion Wear",
      "Bridal Lingerie",
      "Bridal Sets",
      "Honeymoon Lingerie",
      "Holiday Lingerie",
      "Valentine’s Day Lingerie",
    ],
  },
  Sale: {
    name: "Sale",
    subcategories: [
      "Underwear and Intimates Sale",
      "Bras on Sale",
      "Panties on Sale",
      "Lingerie Sets on Sale",
      "Shapewear on Sale",
      "Intimates and Accessories on Sale",
      "Swimwear, Nightwear, and Activewear Sale",
      "Swimwear and Beachwear Sale",
      "Swimsuits on Sale",
      "Cover-Ups on Sale",
      "Beach Accessories on Sale",
      "Activewear on Sale",
      "Nightwear and Loungewear Sale",
      "Pajama Sets on Sale",
      "Nightgowns on Sale",
      "Loungewear on Sale",
    ],
  },
};
